name: Terraform plan
on:
  pull_request:
    branches:
      - main

jobs:
  terrraform-plan:
    name: Terraform plan
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-2'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
      
      