name: Terraform plan
on:
  pull_request:
    branches:
      - feature/actions-terra

jobs:
  terrraform-plan:
    name: Terraform plan
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-2'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: Plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
      
      